-- FINAL FIX: Ensure ALL ScoreCard columns exist in DB
-- This script adds missing columns without dropping data.

-- 1. Hits and Errors
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS home_hits INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS away_hits INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS home_errors INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS away_errors INTEGER DEFAULT 0;

-- 2. Visitor Innings (1-10)
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_inn1 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_inn2 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_inn3 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_inn4 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_inn5 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_ex6 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_ex7 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_ex8 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_ex9 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS vis_ex10 INTEGER DEFAULT 0;

-- 3. Local Innings (1-10)
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_inn1 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_inn2 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_inn3 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_inn4 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_inn5 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_ex6 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_ex7 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_ex8 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_ex9 INTEGER DEFAULT 0;
ALTER TABLE tournament_sets ADD COLUMN IF NOT EXISTS loc_ex10 INTEGER DEFAULT 0;

COMMENT ON COLUMN tournament_sets.vis_inn1 IS 'Visitor Runs Inning 1';
