-- Add Stats columns to Rosters, Teams, and Sets
-- Rosters
ALTER TABLE public.tournament_rosters 
ADD COLUMN IF NOT EXISTS stats_ab INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_h INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_r INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_e_def INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_e_of INTEGER DEFAULT 0;

-- Teams
ALTER TABLE public.tournament_teams 
ADD COLUMN IF NOT EXISTS stats_ab INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_h INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_r INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_e_def INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stats_e_of INTEGER DEFAULT 0;

-- Sets (for Mini Scoreboard R/H/E)
ALTER TABLE public.tournament_sets
ADD COLUMN IF NOT EXISTS home_hits INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS away_hits INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS home_errors INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS away_errors INTEGER DEFAULT 0;
