-- Add explicit inning columns for Scoreboard Sync
ALTER TABLE tournament_sets
ADD COLUMN IF NOT EXISTS vis_inn1 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_inn2 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_inn3 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_inn4 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_inn5 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_ex6 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_ex7 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_ex8 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_ex9 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vis_ex10 INT DEFAULT NULL,

ADD COLUMN IF NOT EXISTS loc_inn1 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_inn2 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_inn3 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_inn4 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_inn5 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_ex6 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_ex7 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_ex8 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_ex9 INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS loc_ex10 INT DEFAULT NULL;
